import os
import requests

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_ANON_KEY")

headers = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json"
}

def fetch_best_startup():
    """Mengambil 1 startup terbaik yang sudah memiliki blueprint."""
    url = f"{SUPABASE_URL}/rest/v1/ideas?select=*&startup_name=not.is.null&order=opportunity_score.desc&limit=1"
    r = requests.get(url, headers=headers)
    if r.status_code == 200 and len(r.json()) > 0:
        return r.json()[0]
    return None

def generate_html(data):
    """Menyusun HTML menggunakan Tailwind CSS."""
    name = data.get("startup_name", "AI Startup")
    pitch = data.get("startup_pitch", "Solving big problems with AI.")
    features = data.get("mvp_spec", [])
    stack = data.get("tech_stack", [])
    problem = data.get("problem", "")

    # Format list features & stack ke HTML
    features_html = "".join([f"<li class='mb-2'>✅ {f}</li>" for f in features])
    stack_html = "".join([f"<span class='bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded'>{s}</span>" for s in stack])

    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{name} - Landing Page</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gray-50 text-gray-900 font-sans">
        <header class="bg-white border-b">
            <div class="container mx-auto px-6 py-16 text-center">
                <h1 class="text-5xl font-bold text-gray-800 mb-4">{name}</h1>
                <p class="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">{pitch}</p>
                <button class="bg-blue-600 text-white px-8 py-3 rounded-lg font-bold hover:bg-blue-700 transition">Get Started</button>
            </div>
        </header>

        <section class="py-16 bg-gray-100">
            <div class="container mx-auto px-6">
                <div class="grid md:grid-cols-2 gap-12 items-center">
                    <div>
                        <h2 class="text-3xl font-bold mb-4">The Problem</h2>
                        <p class="text-gray-600 leading-relaxed">{problem}</p>
                    </div>
                    <div class="bg-white p-8 rounded-xl shadow-sm">
                        <h2 class="text-3xl font-bold mb-4">Core Features (MVP)</h2>
                        <ul class="text-gray-600 list-none text-left">
                            {features_html}
                        </ul>
                    </div>
                </div>
            </div>
        </section>

        <section class="py-16 bg-white">
            <div class="container mx-auto px-6 text-center">
                <h2 class="text-2xl font-bold mb-6">Powered By</h2>
                <div class="flex flex-wrap justify-center gap-4">
                    {stack_html}
                </div>
            </div>
        </section>

        <footer class="py-8 bg-gray-800 text-white text-center">
            <p>&copy; 2026 {name}. Generated by AI Startup Factory.</p>
        </footer>
    </body>
    </html>
    """
    return html_template

def main():
    print("Fetching best startup idea...")
    startup = fetch_best_startup()
    
    if not startup:
        print("No startup blueprint found.")
        return

    print(f"Generating landing page for: {startup['startup_name']}")
    html_content = generate_html(startup)
    
    # Simpan ke file
    filename = "index.html"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print(f"Success! Landing page saved to {os.path.abspath(filename)}")

if __name__ == "__main__":
    main()
